name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --all-features --verbose
      - name: WASI Build
        run: |
          rustup target add wasm32-wasi
          cargo build --all-features --verbose --target=wasm32-wasi
      - name: Run tests
        run: cargo test --verbose --all-features
